export interface HealthGeneralProduct {
  company: string;
  productName: string;
  basePremium: number;
}

export const HEALTH_GENERAL_PRODUCTS: HealthGeneralProduct[] = [
  { company: 'ABL생명', productName: '(무)우리WON건강N더보장종합보험(일반심사형) (월납)', basePremium: 40000 },
  { company: 'ABL생명', productName: '(무)우리WON톡톡튀는여성건강보험(일반심사형) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 New플러스원 건강보험(2601)(무배당,저해약환급금형)_2종(일반고지형) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성웰에이징(Well-Aging)건강보험(2601)(무배당,저해약환급금형) (월납)', basePremium: 40000 },
  { company: '미래에셋생명', productName: 'M-케어 건강보험 무배당 [기본형] (월납)', basePremium: 40000 },
  { company: '미래에셋생명', productName: 'M-케어 건강보험 무배당 [해약환급금이 없는 유형] (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 The퍼스트 건강보험(2601)(무배당,무해약환급금형)_2종(일반고지형) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 The퍼스트 건강보험(2601)(무배당,무해약환급금형)_1종(건강고지형) (월납)', basePremium: 40000 },
  { company: '흥국생명', productName: '(무)흥국생명 다(多)사랑통합보험V2 (월납)', basePremium: 83000 },
  { company: '교보생명', productName: '교보마이플랜건강보험 [D](무배당) (월납)', basePremium: 47000 },
  { company: '교보생명', productName: '교보마이플랜건강보험 (무배당) (월납)', basePremium: 47000 },
  { company: 'DB생명', productName: '(무) 건강100 내가고른 통합보험(2601)(2종:일반형,표준형) (월납)', basePremium: 40000 },
  { company: 'DB생명', productName: '(무) 건강100 내가고른 통합보험(2601)(1종:무사고만기연장형,표준형) (월납)', basePremium: 40000 },
  { company: '라이나생명', productName: '(무)새로담는건강보험(기본형) (월납)', basePremium: 40000 },
  { company: 'NH농협생명', productName: '건강플러스NH통합보험(표준형,무배당)_2601 (월납)', basePremium: 40000 },
  { company: '한화생명', productName: '한화생명 걸음e건강보험 무배당 (월납)', basePremium: 40000 },
  { company: '한화생명', productName: '한화생명 e건강보험 무배당 (월납)', basePremium: 40000 },
  { company: '한화생명', productName: '한화생명 시그니처 H통합건강보험 무배당[일반가입형] (월납)', basePremium: 40000 },
  { company: '한화생명', productName: '한화생명 시그니처 H통합건강보험 무배당(납입면제형)[일반가입형] (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 The(더)Dream 건강보험(2601)(무배당) 100%만기환급형 (월납)', basePremium: 55000 },
  { company: '교보생명', productName: '교보더블업여성건강보험 (무배당) (월납)', basePremium: 90000 },
  { company: '교보생명', productName: '교보더블업여성건강보험 [D](무배당) (월납)', basePremium: 90000 },
  { company: '하나생명', productName: '(무)Top3 건강보험Ⅱ 2대질병보장형 (연납)', basePremium: 40000 },
  { company: '하나생명', productName: '(무)Top3 건강보험Ⅱ 3대질병보장형 (연납)', basePremium: 56000 },
  { company: '하나생명', productName: '(무)Top3 건강보험Ⅱ 암보장형 (연납)', basePremium: 45000 },
  { company: '라이나생명', productName: '무배당라이나당뇨플러스건강보험 (월납)', basePremium: 40000 },
  { company: '라이나생명', productName: '무배당 라이나건강보험(갱신형) (월납)', basePremium: 40000 },
  { company: 'AIA생명', productName: '(무) 백세시대 꼭하나 건강보험 (갱신형) 1형 (월납)', basePremium: 40000 },
  { company: 'NH농협생명', productName: '9988NH건강보험(비갱신형, 일반가입형, 무배당)_2404 (월납)', basePremium: 40000 },
  { company: 'NH농협생명', productName: '핑크케어NH건강보험(무배당) (월납)', basePremium: 45000 },
  { company: 'NH농협생명', productName: '백세팔팔NH건강보험(비갱신형,무배당)_2506 (월납)', basePremium: 40000 },
  { company: '교보라이프플래닛', productName: '(무)교보라플 여성건강보험(순수보장형) (월납)', basePremium: 40000 },
  { company: '교보라이프플래닛', productName: '(무)교보라플 여성건강보험(만기환급형) (월납)', basePremium: 76000 },
  { company: '흥국생명', productName: '(무)흥국생명다재다능종합보험 (월납)', basePremium: 40000 },
  { company: 'DB생명', productName: 'KDB든든한 건강보험(암보장)(무) (월납)', basePremium: 40000 },
  { company: 'ABL생명', productName: '(무)우리WON인터넷네개딱!패키지건강보험(갱신형) (월납)', basePremium: 40000 },
  { company: 'ABL생명', productName: '(무)우리WON건강N더보장종합보험(갱신형)(일반심사형) (월납)', basePremium: 40000 },
  { company: '라이나생명', productName: '(무)골라담는건강보험(갱신형)_2형 (월납)', basePremium: 40000 },
  { company: '라이나생명', productName: '(무)골라담는건강보험(갱신형)_1형 (월납)', basePremium: 40000 },
  { company: '교보라이프플래닛', productName: '(무)교보라플 맞춤건강종합보험(갱신형) (월납)', basePremium: 40000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0 (무) 3종(납입면제형,기본형) (월납)', basePremium: 90000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0 (무) 1종(납입면제 강화형,기본형) (월납)', basePremium: 90000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0(건강관리형) (무) 1종(납입면제 강화형,기본형) (월납)', basePremium: 85000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0(건강관리형) (무) 3종(납입면제형,기본형) (월납)', basePremium: 90000 },
  { company: '롯데손보', productName: '(무) let:smile 종합건강보험(더끌림 포우먼)(2601)_1종(100세만기, 일반형, 납입면제형) (월납)', basePremium: 46000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0_CM (무) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 가족대표건강보험(2605)(무배당,무해약환급금형)_2종(일반고지형) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 가족대표건강보험(2605)(무배당,무해약환급금형)_1종(건강고지형) (월납)', basePremium: 40000 },
  { company: 'DB생명', productName: '(무)실속N 7대질병 건강보험(2601)(표준형) (월납)', basePremium: 40000 },
  { company: 'DB생명', productName: '(무)백년친구 New 내가고른 건강보험(2601)(표준형) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 4180 인생대표 건강보험(2604)(무배당,무해약환급금형)_2종(일반고지형) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 4180 인생대표 건강보험(2604)(무배당,무해약환급금형)_1종(건강고지형 10년고지) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 1540 청춘대표 건강보험(2604)(무배당,무해약환급금형)_2종(일반고지형) (월납)', basePremium: 40000 },
  { company: '삼성생명', productName: '삼성 1540 청춘대표 건강보험(2604)(무배당,무해약환급금형)_1종(건강고지형 10년고지) (월납)', basePremium: 40000 },
  { company: '교보생명', productName: '교보밸런스건강보험 (무배당) (월납)', basePremium: 40000 },
  { company: '교보생명', productName: '교보밸런스건강보험 [D](무배당) (월납)', basePremium: 40000 },
  { company: 'AIA생명', productName: '(무) 뇌심 바로케어 건강보험 1형 (월납)', basePremium: 40000 },
  { company: '한화생명', productName: '한화생명 시그니처 H통합보험 무배당[일반가입형] (월납)', basePremium: 40000 },
  { company: '한화생명', productName: '한화생명 시그니처 H통합보험 무배당(납입면제형)[일반가입형] (월납)', basePremium: 40000 },
  { company: '교보생명', productName: '교보평생건강보험 PLUS (무배당)_일반형 (월납)', basePremium: 90000 },
  { company: '한화손보', productName: '한화 다이렉트 시그니처 여성 건강보험4.0 (무)2604 (월납)', basePremium: 82000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0 (무)2604 3종(납입면제형,기본형) (월납)', basePremium: 90000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0 (무)2604 1종(납입면제 강화형,기본형) (월납)', basePremium: 90000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0(건강관리형) (무)2604 3종(납입면제형,기본형) (월납)', basePremium: 90000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험4.0(건강관리형) (무)2604 1종(납입면제 강화형,기본형) (월납)', basePremium: 90000 },
  { company: '롯데손보', productName: '(무) let:smile 종합건강보험(더끌림 포우먼)(2604)_1종(100세만기, 일반형, 납입면제형) (월납)', basePremium: 52000 },
  { company: '하나손보', productName: '무배당 하나더스마트 여성건강보험 1종(세만기형, 표준형) (월납)', basePremium: 41000 },
  { company: '하나손보', productName: '무배당 하나더스마트 여성건강보험 3종(갱신형, 표준형) (월납)', basePremium: 40000 },
  { company: '삼성화재', productName: '삼성화재 마이헬스 파트너 종합보험 (월납)', basePremium: 65000 },
  { company: '메리츠화재', productName: '메리츠화재 내Mom같은 건강보험 (월납)', basePremium: 68000 },
  { company: 'DB손보', productName: 'DB손보 나에게맞춘 간편건강보험 (월납)', basePremium: 67000 },
  { company: '현대해상', productName: '현대해상 퍼펙트플러스 종합보험 (월납)', basePremium: 72000 },
  { company: 'KB손보', productName: 'KB 오텐텐 건강보험 (월납)', basePremium: 70000 },
  { company: '한화손보', productName: '한화 시그니처 여성 건강보험 (월납)', basePremium: 63000 },
  { company: '흥국화재', productName: '흥국화재 행복을다주는 가족사랑보험 (월납)', basePremium: 59000 },
];
