export interface AccidentProduct {
  company: string;
  productName: string;
  basePremium: number;
}

export const ACCIDENT_PRODUCTS: AccidentProduct[] = [
  { company: '특약', productName: '재해장해특약 무배당 (월납)', basePremium: 5000 },
  { company: '특약', productName: '재해사망특약 무배당 (월납)', basePremium: 5000 },
  { company: '한화생명', productName: '한화생명 간편가입 포켓골절보험 무배당 (일시납)', basePremium: 5000 },
  { company: 'ABL생명', productName: '(무)더나은안심보험_2형(상해보장형) (월납)', basePremium: 50000 },
  { company: '삼성생명', productName: '삼성 마음모아 미니상해보험(2403)(무배당) (월납)', basePremium: 5000 },
  { company: '삼성생명', productName: '삼성 s교통상해보험(2501)(무배당) (월납)', basePremium: 5000 },
  { company: '주계약', productName: '재해장해보험금 (월납)', basePremium: 5300 },
  { company: '흥국생명', productName: '(무)처음만난흥국생명상해보험 (월납)', basePremium: 5000 },
  { company: '교보생명', productName: '교보e대중교통안심보험 (무배당) (월납)', basePremium: 5000 },
  { company: '교보생명', productName: '교보e교통안심보험 (무배당) (월납)', basePremium: 5000 },
  { company: '교보생명', productName: '교보상해보험 [D](무배당)[만기환급형(100%)] (월납)', basePremium: 50000 },
  { company: '동양생명', productName: '(무)엔젤안심보험(상해보장형,표준형) (월납)', basePremium: 50000 },
  { company: '주계약', productName: '재해사망보험금 (월납)', basePremium: 26800 },
  { company: '동양생명', productName: '(무)우리WON하는미니상해보험 (월납)', basePremium: 5000 },
  { company: '동양생명', productName: '(무)우리WON하는mini교통재해보험 (월납)', basePremium: 5000 },
  { company: '동양생명', productName: '(무)엔젤상해보험 (월납)', basePremium: 22000 },
  { company: '메트라이프생명', productName: '무배당 메트라이프 mini 재해보험 (월납)', basePremium: 5000 },
  { company: '메트라이프생명', productName: '무배당 뼈 미니 재해골절보험 (월납)', basePremium: 5000 },
  { company: 'KB라이프생명', productName: 'KB 지켜주는 교통안심보험 무배당 (월납)', basePremium: 5000 },
  { company: 'NH농협생명', productName: '심플한NH재해보험(무배당) (월납)', basePremium: 5000 },
  { company: 'NH농협생명', productName: '효밍아웃NH부모님안전보험(무배당)_2404 (월납)', basePremium: 9000 },
  { company: 'NH농협생명', productName: '농작업근로자NH안전보험(무배당) (월납)', basePremium: 30300 },
  { company: 'NH농협생명', productName: '온라인농업인NH안전보험(무배당) (월납)', basePremium: 50000 },
  { company: 'NH농협생명', productName: '농업인NH안전보험(무배당) (월납)', basePremium: 50000 },
  { company: '주계약', productName: '안심보장플러스 재해사망보험금 (월납)', basePremium: 50000 },
  { company: '교보라이프플래닛', productName: '(무)교보라플안심보험(상해보장형, 표준형) (월납)', basePremium: 50000 },
  { company: '신한라이프생명', productName: '신한SOL다치면속상해보험 mini(무배당) (월납)', basePremium: 8600 },
  { company: '메리츠화재', productName: '(무) 메리츠 상해안심보험2601 (월납)', basePremium: 23400 },
  { company: '롯데손보', productName: '(무) 다쳤을땐 상해보험(2601) (월납)', basePremium: 10300 },
  { company: '롯데손보', productName: '(무) let:care 상해보험(2601) (월납)', basePremium: 16200 },
  { company: '롯데손보', productName: '(무) let:care 생활상해종합보험(주택플러스)(2602) (월납)', basePremium: 50000 },
  { company: '', productName: '[건강]보험료 납입면제대상(특정상해진단수술) (월납)', basePremium: 50000 },
  { company: '현대해상', productName: '(무)현대해상하이퍼스트상해보험(Hi2601)/(무)하이퍼스트상해보험(Hi2601) 2종 (월납)', basePremium: 5000 },
  { company: '현대해상', productName: '(무)현대해상하이퍼스트상해보험(Hi2601)/(무)하이퍼스트상해보험(Hi2601) 1종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'KB든든안심상해보험Ⅱ(무배당)(26.01)_2종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'CEO안심상해보험Ⅱ(무배당)(26.01)_3종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'CEO안심상해보험Ⅱ(무배당)(26.01)_2종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'CEO안심상해보험Ⅱ(무배당)(26.01)_1종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'KB든든안심상해보험Ⅱ(무배당)(26.01)_3종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'KB든든안심상해보험Ⅱ(무배당)(26.01)_1종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'KB VIP상해보험(무배당)(26.01) (월납)', basePremium: 35400 },
  { company: 'KB손보', productName: 'KB 다치면 보장받는 플러스 상해보험(무배당)(26.01)_2종(세만기) (월납)', basePremium: 45300 },
  { company: 'KB손보', productName: 'KB 다치면 보장받는 플러스 상해보험(무배당)(26.01)_1종(연만기 자동갱신형) (월납)', basePremium: 37500 },
  { company: 'DB손보', productName: '(무)New상해안심보험2601((금리확정형)고급플랜) (월납)', basePremium: 5000 },
  { company: 'DB손보', productName: '(무)New상해안심보험2601((금리연동형)종합플랜) (월납)', basePremium: 12200 },
  { company: 'DB손보', productName: '(무)New상해안심보험2601((금리연동형)고급플랜) (월납)', basePremium: 5000 },
  { company: 'DB손보', productName: '(무)만상형통상해보험2601(1종) (월납)', basePremium: 11100 },
  { company: 'DB손보', productName: '(무)만상형통상해보험2601(2종) (월납)', basePremium: 22400 },
  { company: 'AXA손보', productName: '(무)AXA간편상해보험2601 (월납)', basePremium: 5000 },
  { company: '하나손보', productName: '무배당 하나더넥스트 상해보험(방카)(2601) (월납)', basePremium: 10100 },
  { company: 'AIG손보', productName: '무배당 AIG 꼭 필요한 상해종합보험2601 (월납)', basePremium: 8100 },
  { company: 'AIG손보', productName: '무배당 AIG 꼭 필요한 상해보험2601(2종) (월납)', basePremium: 8100 },
  { company: 'AIG손보', productName: '무배당 AIG 꼭 필요한 상해보험2601(1종) (월납)', basePremium: 5000 },
  { company: 'AIG손보', productName: '무배당 AIG 참쉬운상해보험2601 (월납)', basePremium: 8500 },
  { company: '에이스손보', productName: '(무)이젠 나만의 상해보험(갱신형) (월납)', basePremium: 13300 },
  { company: '농협손보', productName: '(무) NH위너스상해보험[1종:VIP플랜(금리확정형)]2601 (월납)', basePremium: 6000 },
  { company: '농협손보', productName: '(무) NH위너스상해보험[2종:VIP플러스플랜(금리확정형)]2601 (월납)', basePremium: 50000 },
  { company: '농협손보', productName: '(무) NH위너스상해보험[3종:상해플랜(금리연동형)]2601 (월납)', basePremium: 5000 },
  { company: '농협손보', productName: '(무) 헤아림상해치료보험[1종:일반심사형]2601 (월납)', basePremium: 20200 },
  { company: '농협손보', productName: '(무) 헤아림상해치료보험[2종:320간편심사형]2601 (월납)', basePremium: 26800 },
  { company: '특약', productName: '무배당 재해장해보장특약Ⅰ (월납)', basePremium: 50000 },
  { company: '특약', productName: '무배당 재해장해보장특약I (월납)', basePremium: 50000 },
  { company: '특약', productName: '재해사망보험금 (월납)', basePremium: 5000 },
  { company: '롯데손보', productName: '(무) let:care 상해보험(2604) (월납)', basePremium: 23900 },
  { company: '롯데손보', productName: '(무) let:care 생활상해종합보험(주택플러스)(2604) (월납)', basePremium: 5000 },
  { company: '롯데손보', productName: '(무) 다쳤을땐 상해보험(2604) (월납)', basePremium: 10400 },
  { company: '현대해상', productName: '(무)현대해상하이퍼스트상해보험(Hi2605)/(무)하이퍼스트상해보험(Hi2605) 2종 (월납)', basePremium: 5000 },
  { company: '현대해상', productName: '(무)현대해상하이퍼스트상해보험(Hi2605)/(무)하이퍼스트상해보험(Hi2605) 1종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'KB든든안심상해보험Ⅱ(무배당)(26.05)_3종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'KB든든안심상해보험Ⅱ(무배당)(26.05)_2종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'KB든든안심상해보험Ⅱ(무배당)(26.05)_1종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'CEO안심상해보험Ⅱ(무배당)(26.05)_3종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'CEO안심상해보험Ⅱ(무배당)(26.05)_2종 (월납)', basePremium: 5000 },
  { company: 'KB손보', productName: 'CEO안심상해보험Ⅱ(무배당)(26.05)_1종 (월납)', basePremium: 5000 },
  { company: 'DB손보', productName: '(무)New상해안심보험2604((금리확정형)고급플랜) (월납)', basePremium: 5000 },
  { company: 'DB손보', productName: '(무)New상해안심보험2604((금리연동형)종합플랜) (월납)', basePremium: 7200 },
  { company: 'DB손보', productName: '(무)New상해안심보험2604((금리연동형)고급플랜) (월납)', basePremium: 5000 },
  { company: 'DB손보', productName: '(무)만상형통상해보험2604(1종) (월납)', basePremium: 11100 },
  { company: 'DB손보', productName: '(무)만상형통상해보험2604(2종) (월납)', basePremium: 22400 },
  { company: 'AXA손보', productName: '(무)AXA간편상해보험2604 (월납)', basePremium: 5000 },
  { company: '하나손보', productName: '무배당 하나더넥스트 상해보험(방카)(2604) (월납)', basePremium: 9900 },
  { company: '하나손보', productName: '무배당 하나더퍼스트 상해보험(다이렉트) (월납)', basePremium: 5000 },
  { company: 'AIG손보', productName: '무배당 AIG 꼭 필요한 상해종합보험2604 (월납)', basePremium: 8500 },
  { company: 'AIG손보', productName: '무배당 AIG 꼭 필요한 상해보험2604(2종) (월납)', basePremium: 8500 },
  { company: 'AIG손보', productName: '무배당 AIG 꼭 필요한 상해보험2604(1종) (월납)', basePremium: 5000 },
  { company: 'AIG손보', productName: '무배당 AIG 참쉬운상해보험2604 (월납)', basePremium: 8100 },
  { company: '삼성화재', productName: '삼성화재 다이렉트 착한상해보험 (월납)', basePremium: 12000 },
  { company: '현대해상', productName: '현대해상 다이렉트 든든상해보험 (월납)', basePremium: 13000 },
  { company: 'DB손보', productName: '프로미라이프 참좋은상해보험 (월납)', basePremium: 12500 },
  { company: 'KB손보', productName: 'KB 다이렉트 플러스상해보험 (월납)', basePremium: 13500 },
  { company: '메리츠화재', productName: '메리츠화재 올바른상해보험 (월납)', basePremium: 14000 },
];
