with open('src/components/AnalysisDashboard.tsx', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_block = (
    '              {/* Diet 카드 헤더 — 리모델링 vs 일반 */}\n'
    '              {isRemodeling ? (() => {\n'
    '                const policies: any[] = (analysis as any)._remodelingCoverage?.policies || [];\n'
    '                const totalCurrent = policies.reduce((s: number, p: any) => s + p.monthly_premium, 0);\n'
    '                const totalDiet = Math.round(totalCurrent * 0.785);\n'
    '                const totalSaving = totalCurrent - totalDiet;\n'
    '                const hasKBDup = policies.filter((p: any) => p.insurance_company === \'KB손해보험\').length >= 2;\n'
    '                return (\n'
    '                  <>\n'
    '                    <div className="flex items-center gap-3 mb-6 relative z-10">\n'
    '                      <div className="w-16 h-16 bg-blue-600 text-white rounded-3xl flex items-center justify-center shadow-lg shadow-blue-200 group-hover:rotate-[360deg] transition-transform duration-1000">\n'
    '                        <Zap className="w-8 h-8 fill-current" />\n'
    '                      </div>\n'
    '                      <div>\n'
    '                        <h4 className="text-xl font-black tracking-tighter text-blue-900 uppercase">7개 보험 동시 리밸런싱</h4>\n'
    '                        <p className="text-sm text-blue-400 font-bold">보장은 그대로 · 보험료만 낮춘다</p>\n'
    '                      </div>\n'
    '                    </div>\n'
    '                    <div className="flex items-center gap-3 mb-8 bg-white/70 rounded-2xl p-5 border border-blue-100 relative z-10">\n'
    '                      <div className="flex-1 text-center">\n'
    '                        <span className="text-[9px] font-black text-red-400 block uppercase mb-1">현재 월 납입 합계</span>\n'
    '                        <span className="text-2xl font-black text-red-500">{totalCurrent.toLocaleString()}</span>\n'
    '                        <span className="text-xs font-black text-red-400">원</span>\n'
    '                      </div>\n'
    '                      <div className="flex flex-col items-center gap-1 flex-shrink-0">\n'
    '                        <span className="text-emerald-600 text-[9px] font-black bg-emerald-50 border border-emerald-200 rounded-full px-2 py-0.5">-{totalSaving.toLocaleString()}원</span>\n'
    '                        <span className="text-2xl text-blue-400 font-black">→</span>\n'
    '                      </div>\n'
    '                      <div className="flex-1 text-center">\n'
    '                        <span className="text-[9px] font-black text-blue-500 block uppercase mb-1">리밸런싱 후</span>\n'
    '                        <span className="text-2xl font-black text-blue-600">{totalDiet.toLocaleString()}</span>\n'
    '                        <span className="text-xs font-black text-blue-400">원</span>\n'
    '                      </div>\n'
    '                    </div>\n'
    '                    <ul className="space-y-3 mb-10 relative z-10">\n'
    '                      <li className="flex items-center gap-3 text-sm font-bold text-gray-700">\n'
    '                        <div className="w-6 h-6 rounded-full bg-indigo-100 flex items-center justify-center flex-shrink-0"><ShieldCheck className="w-4 h-4 text-indigo-500" /></div>\n'
    '                        종신보험 — 사망 1억 보장 동일 유지\n'
    '                      </li>\n'
    '                      <li className="flex items-center gap-3 text-sm font-bold text-gray-700">\n'
    '                        <div className="w-6 h-6 rounded-full bg-purple-100 flex items-center justify-center flex-shrink-0"><ShieldCheck className="w-4 h-4 text-purple-500" /></div>\n'
    '                        운전자보험 — 형사합의·벌금·변호사 보장 동일 유지\n'
    '                      </li>\n'
    '                      <li className="flex items-center gap-3 text-sm font-bold text-gray-700">\n'
    '                        <div className="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center flex-shrink-0"><ShieldCheck className="w-4 h-4 text-blue-500" /></div>\n'
    '                        종합건강보험 — 암·뇌혈관·심장 진단비 보장 동일 유지\n'
    '                      </li>\n'
    '                      {hasKBDup && (\n'
    '                        <li className="flex items-center gap-3 text-sm font-bold text-amber-700 bg-amber-50 rounded-xl px-3 py-2 border border-amber-100">\n'
    '                          <span className="w-6 h-6 rounded-full bg-amber-200 flex items-center justify-center flex-shrink-0 text-xs">⚠️</span>\n'
    '                          KB손해보험 동일 상품 2개 중복 → 1개 정리 시 추가 절감 가능\n'
    '                        </li>\n'
    '                      )}\n'
    '                    </ul>\n'
    '                  </>\n'
    '                );\n'
    '              })() : (\n'
    '                <>\n'
    '                  <div className="absolute top-0 right-0 p-8 opacity-10 rotate-45 transform"><Zap className="w-32 h-32 text-blue-500" /></div>\n'
    '                  <div className="w-16 h-16 bg-blue-600 text-white rounded-3xl flex items-center justify-center mb-10 shadow-lg shadow-blue-200 group-hover:rotate-[360deg] transition-transform duration-1000 relative z-10"><Zap className="w-8 h-8 fill-current" /></div>\n'
    '                  <h4 className="text-2xl font-black mb-1 tracking-tighter text-blue-900 group-hover:text-blue-600 transition-colors uppercase">{result.recommendations.diet.title}</h4>\n'
    '                  {result.recommendations.diet.companyName && (\n'
    '                    <div className="flex flex-wrap items-center gap-y-1.5 mb-4">\n'
    '                      <span className="inline-block px-3 py-1 bg-blue-100 text-blue-700 rounded-lg text-[0.6rem] font-black mr-2 uppercase tracking-widest">{result.recommendations.diet.companyName}</span>\n'
    '                      <span className="text-xs font-bold text-slate-500 italic break-keep">{result.recommendations.diet.productName}</span>\n'
    '                    </div>\n'
    '                  )}\n'
    '                  <p className="text-sm text-gray-400 font-bold leading-relaxed mb-10 min-h-[4rem]">{result.recommendations.diet.description}</p>\n'
    '                  <div className="mb-10 border-b border-gray-50 pb-10">\n'
    '                    <span className="text-[0.65rem] font-black text-gray-300 uppercase tracking-widest block mb-3">{isCar ? \'연 예상 보험료\' : \'월 예상 보험료\'}</span>\n'
    '                    <div className="flex items-baseline gap-1">\n'
    '                      <span className="text-6xl font-black text-blue-600 tracking-tighter">{Math.round(isCar ? result.recommendations.diet.estimatedPremium * 12 : result.recommendations.diet.estimatedPremium).toLocaleString()}</span>\n'
    '                      <span className="text-2xl font-black text-gray-900">원</span>\n'
    '                    </div>\n'
    '                  </div>\n'
    '                  <ul className="space-y-6 flex-1 mb-12">\n'
    '                    {result.recommendations.diet.coverageChanges.map((change, i) => (\n'
    '                      <li key={i} className="flex items-center gap-4 text-sm font-bold text-gray-600">\n'
    '                        <div className="w-6 h-6 rounded-full bg-blue-50 flex items-center justify-center flex-shrink-0"><ShieldCheck className="w-4 h-4 text-blue-500" /></div>\n'
    '                        {change}\n'
    '                      </li>\n'
    '                    ))}\n'
    '                  </ul>\n'
    '                </>\n'
    '              )}\n'
)

# Replace lines 612-658 (0-indexed 611-657)
new_lines = lines[:611] + [new_block] + lines[658:]

with open('src/components/AnalysisDashboard.tsx', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f'Done. Lines: {len(lines)} -> {len(new_lines)}')
