with open('src/components/AnalysisDashboard.tsx', 'r', encoding='utf-8') as f:
    lines = f.readlines()

UPGRADE_COMPANIES = ['DB손해보험', 'KB손해보험', '한화손해보험', '현대해상', '삼성화재', '메리츠화재']

new_block = (
    '              {/* Upgrade 카드 헤더 — 리모델링 vs 일반 */}\n'
    '              {isRemodeling ? (() => {\n'
    '                const policies: any[] = (analysis as any)._remodelingCoverage?.policies || [];\n'
    '                const totalCurrent = policies.reduce((s: number, p: any) => s + p.monthly_premium, 0);\n'
    '                const UPCO = [\'DB손해보험\',\'KB손해보험\',\'한화손해보험\',\'현대해상\',\'삼성화재\',\'메리츠화재\'];\n'
    '                const rows = policies.map((p: any, i: number) => {\n'
    '                  const isDriver = p.product_name.includes(\'운전자\');\n'
    '                  const isWhole = p.product_name.includes(\'종신\');\n'
    '                  const company = UPCO[i % UPCO.length];\n'
    '                  const prodType = isWhole ? \'무배당 VIP 종신 업그레이드 보험\'\n'
    '                    : isDriver ? \'무배당 VIP 운전자 업그레이드 보험\'\n'
    '                    : \'무배당 VIP 마스터 업그레이드 건강보험\';\n'
    '                  const cancerBonus = isWhole || isDriver ? 0 : [2000,1800,1600,1400,1200,1000][i % 6] * 10000;\n'
    '                  const brainBonus  = isWhole || isDriver ? 0 : [1000,900,800,700,600,500][i % 6] * 10000;\n'
    '                  const heartBonus  = isWhole || isDriver ? 0 : [1000,900,800,700,600,500][i % 6] * 10000;\n'
    '                  return { orig: p, company, prodType, cancerBonus, brainBonus, heartBonus };\n'
    '                });\n'
    '                return (\n'
    '                  <>\n'
    '                    <div className="flex items-center gap-3 mb-6 relative z-10">\n'
    '                      <div className="w-16 h-16 bg-orange-500 text-white rounded-3xl flex items-center justify-center shadow-lg shadow-orange-200 animate-pulse">\n'
    '                        <Zap className="w-8 h-8 fill-current" />\n'
    '                      </div>\n'
    '                      <div>\n'
    '                        <h4 className="text-xl font-black tracking-tighter text-orange-400 uppercase">7개 보험 동시 업그레이드</h4>\n'
    '                        <p className="text-sm text-slate-400 font-bold">보험료는 그대로 · 보장만 더 든든하게</p>\n'
    '                      </div>\n'
    '                    </div>\n'
    '                    <div className="flex items-center gap-3 mb-8 bg-white/10 rounded-2xl p-5 border border-white/10 relative z-10">\n'
    '                      <div className="flex-1 text-center">\n'
    '                        <span className="text-[9px] font-black text-slate-400 block uppercase mb-1">현재 월 납입 합계</span>\n'
    '                        <span className="text-2xl font-black text-slate-300">{totalCurrent.toLocaleString()}</span>\n'
    '                        <span className="text-xs font-black text-slate-400">원</span>\n'
    '                      </div>\n'
    '                      <div className="flex flex-col items-center gap-1 flex-shrink-0">\n'
    '                        <span className="text-orange-400 text-[9px] font-black bg-orange-500/20 border border-orange-500/30 rounded-full px-2 py-0.5">동일 유지</span>\n'
    '                        <span className="text-2xl text-orange-400 font-black">→</span>\n'
    '                      </div>\n'
    '                      <div className="flex-1 text-center">\n'
    '                        <span className="text-[9px] font-black text-orange-300 block uppercase mb-1">보장 강화 후</span>\n'
    '                        <span className="text-2xl font-black text-orange-400">{totalCurrent.toLocaleString()}</span>\n'
    '                        <span className="text-xs font-black text-orange-300">원</span>\n'
    '                      </div>\n'
    '                    </div>\n'
    '                    {/* Per-policy upgrade rows */}\n'
    '                    <div className="space-y-3 mb-10 relative z-10">\n'
    '                      {rows.map((r: any, i: number) => (\n'
    '                        <div key={i} className="flex items-center gap-2">\n'
    '                          {/* 현재 보험 */}\n'
    '                          <div className="flex-1 bg-white/5 border border-white/10 rounded-2xl px-4 py-3">\n'
    '                            <span className="text-[8px] font-black text-slate-400 block uppercase mb-0.5">현재 보험</span>\n'
    '                            <span className="text-[9px] font-black text-slate-300 block">{r.orig.insurance_company}</span>\n'
    '                            <span className="text-xs font-bold text-white leading-snug line-clamp-2">{r.orig.product_name.split(\'(\')[0].trim()}</span>\n'
    '                            <span className="text-sm font-black text-slate-300 mt-1 block">{r.orig.monthly_premium.toLocaleString()}원</span>\n'
    '                          </div>\n'
    '                          {/* 보강 표시 */}\n'
    '                          <div className="flex flex-col items-center gap-1 flex-shrink-0 w-20">\n'
    '                            {r.cancerBonus > 0 ? (\n'
    '                              <span className="text-[8px] font-black text-orange-300 bg-orange-500/20 border border-orange-500/30 rounded-full px-1.5 py-0.5 whitespace-nowrap">암 +{r.cancerBonus/10000}천만</span>\n'
    '                            ) : (\n'
    '                              <span className="text-[8px] font-black text-slate-400">보장 강화</span>\n'
    '                            )}\n'
    '                            <span className="text-2xl text-orange-400 font-black">→</span>\n'
    '                          </div>\n'
    '                          {/* 업그레이드 보험 */}\n'
    '                          <div className="flex-1 bg-orange-500/10 border border-orange-500/30 rounded-2xl px-4 py-3">\n'
    '                            <span className="text-[8px] font-black text-orange-300 block uppercase mb-0.5">🚀 업그레이드</span>\n'
    '                            <span className="text-[9px] font-black text-orange-400 block">{r.company}</span>\n'
    '                            <span className="text-xs font-bold text-white leading-snug">{r.prodType}</span>\n'
    '                            <span className="text-sm font-black text-orange-300 mt-1 block">{r.orig.monthly_premium.toLocaleString()}원 (동일)</span>\n'
    '                          </div>\n'
    '                        </div>\n'
    '                      ))}\n'
    '                    </div>\n'
    '                    {/* 보강 요약 */}\n'
    '                    <div className="grid grid-cols-3 gap-3 relative z-10">\n'
    '                      <div className="bg-orange-500/10 border border-orange-500/20 rounded-2xl p-4 text-center">\n'
    '                        <span className="text-[9px] font-black text-orange-300 block uppercase">암진단비 추가</span>\n'
    '                        <span className="text-lg font-black text-orange-400">최대 +2,000만원</span>\n'
    '                      </div>\n'
    '                      <div className="bg-orange-500/10 border border-orange-500/20 rounded-2xl p-4 text-center">\n'
    '                        <span className="text-[9px] font-black text-orange-300 block uppercase">뇌혈관 추가</span>\n'
    '                        <span className="text-lg font-black text-orange-400">최대 +1,000만원</span>\n'
    '                      </div>\n'
    '                      <div className="bg-orange-500/10 border border-orange-500/20 rounded-2xl p-4 text-center">\n'
    '                        <span className="text-[9px] font-black text-orange-300 block uppercase">심장 추가</span>\n'
    '                        <span className="text-lg font-black text-orange-400">최대 +1,000만원</span>\n'
    '                      </div>\n'
    '                    </div>\n'
    '                  </>\n'
    '                );\n'
    '              })() : (\n'
    '                <>\n'
    '                  <div className="w-16 h-16 bg-orange-500 text-white rounded-3xl flex items-center justify-center mb-10 shadow-[0_15px_30px_-5px_rgba(255,107,0,0.5)] animate-pulse"><Zap className="w-8 h-8 fill-current" /></div>\n'
    '                  <h4 className="text-2xl font-black mb-1 tracking-tighter text-orange-400 uppercase">{result.recommendations.upgrade.title}</h4>\n'
    '                  {result.recommendations.upgrade.companyName && (\n'
    '                    <div className="flex flex-wrap items-center gap-y-1.5 mb-4 animate-in fade-in slide-in-from-left-2 transition-all">\n'
    '                      <span className="inline-block px-3 py-1 bg-orange-500 text-white rounded-lg text-[0.6rem] font-black mr-2 uppercase tracking-widest">{result.recommendations.upgrade.companyName}</span>\n'
    '                      <span className="text-xs font-bold text-slate-400 italic break-keep">{result.recommendations.upgrade.productName}</span>\n'
    '                    </div>\n'
    '                  )}\n'
    '                  <p className="text-sm text-slate-400 font-bold leading-relaxed mb-10 min-h-[4rem]">{result.recommendations.upgrade.description}</p>\n'
    '                  <div className="mb-10 border-b border-white/5 pb-10">\n'
    '                    <span className="text-[0.65rem] font-black text-slate-600 uppercase tracking-widest block mb-3">{isCar ? \'연 예상 보험료\' : \'월 예상 보험료\'}</span>\n'
    '                    <div className="flex items-baseline gap-1">\n'
    '                      <span className="text-6xl font-black text-orange-500 tracking-tighter">{Math.round(isCar ? result.recommendations.upgrade.estimatedPremium * 12 : result.recommendations.upgrade.estimatedPremium).toLocaleString()}</span>\n'
    '                      <span className="text-2xl font-black text-white">원</span>\n'
    '                    </div>\n'
    '                  </div>\n'
    '                  <ul className="space-y-6 flex-1 mb-12">\n'
    '                    {result.recommendations.upgrade.coverageChanges.map((change, i) => (\n'
    '                      <li key={i} className="flex items-center gap-4 text-sm font-bold">\n'
    '                        <div className="w-6 h-6 rounded-full bg-orange-500/20 flex items-center justify-center flex-shrink-0"><ShieldCheck className="w-4 h-4 text-orange-500" /></div>\n'
    '                        {change}\n'
    '                      </li>\n'
    '                    ))}\n'
    '                  </ul>\n'
    '                </>\n'
    '              )}\n'
)

# Lines 803-895 (0-indexed 802-894)
new_lines = lines[:802] + [new_block] + lines[895:]

with open('src/components/AnalysisDashboard.tsx', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f'Done. Lines: {len(lines)} -> {len(new_lines)}')
