-- ============================================================================
-- 📌 [Supabase SQL 고도화 마이그레이션] 28개 보험 정밀 옵션 & 보험료 변동 수식
-- ============================================================================

-- 1. pgvector 확장기능 활성화
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. insurance_knowledge_base (테이블 생성 및 컬럼 보완)
CREATE TABLE IF NOT EXISTS public.insurance_knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT ''
);

ALTER TABLE public.insurance_knowledge_base ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.insurance_knowledge_base ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.insurance_knowledge_base ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE public.insurance_knowledge_base ADD COLUMN IF NOT EXISTS keywords TEXT[] DEFAULT '{}';
ALTER TABLE public.insurance_knowledge_base ADD COLUMN IF NOT EXISTS embedding vector(768);
ALTER TABLE public.insurance_knowledge_base ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());
ALTER TABLE public.insurance_knowledge_base ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());

CREATE INDEX IF NOT EXISTS idx_knowledge_category ON public.insurance_knowledge_base(category);

-- ----------------------------------------------------------------------------
-- 3. insurance_calculation_rules (정밀 입력 옵션 & 보험료 변동 수식 컬럼 추가)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.insurance_calculation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT
);

ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS engine_name TEXT;
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS deficiency_rules JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS recommendation_plans JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS input_options_schema JSONB DEFAULT '{}'::jsonb;  -- 🎛️ UI 정밀 입력 옵션 필드
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS premium_factor_matrix JSONB DEFAULT '{}'::jsonb;-- 💰 옵션 변동에 따른 보험료 증감 수식
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS formula_explanation TEXT;
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS embedding vector(768);
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());
ALTER TABLE public.insurance_calculation_rules ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());

-- UNIQUE 제약 조건 안전하게 추가
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'unique_calculation_category'
    ) THEN
        ALTER TABLE public.insurance_calculation_rules ADD CONSTRAINT unique_calculation_category UNIQUE (category);
    END IF;
END $$;

-- ----------------------------------------------------------------------------
-- 4. insurance_rate_tables (보험사별 연령/성별 요율 계수)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.insurance_rate_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT
);

ALTER TABLE public.insurance_rate_tables ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.insurance_rate_tables ADD COLUMN IF NOT EXISTS company_name TEXT;
ALTER TABLE public.insurance_rate_tables ADD COLUMN IF NOT EXISTS product_name TEXT;
ALTER TABLE public.insurance_rate_tables ADD COLUMN IF NOT EXISTS age_gender_factors JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.insurance_rate_tables ADD COLUMN IF NOT EXISTS base_premium_formula TEXT;
ALTER TABLE public.insurance_rate_tables ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW());

-- ----------------------------------------------------------------------------
-- 5. RPC 함수 확장: match_calculation_rules (옵션 스키마 & 변동 수식 포함 반환)
-- ----------------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.match_calculation_rules(vector, float, int);
DROP FUNCTION IF EXISTS public.match_calculation_rules(vector(768), float, int);

CREATE OR REPLACE FUNCTION public.match_calculation_rules (
  query_embedding vector(768),
  match_threshold float DEFAULT 0.3,
  match_count int DEFAULT 3
)
RETURNS TABLE (
  id bigint,
  category text,
  engine_name text,
  deficiency_rules jsonb,
  recommendation_plans jsonb,
  input_options_schema jsonb,
  premium_factor_matrix jsonb,
  formula_explanation text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    cr.id,
    cr.category,
    cr.engine_name,
    cr.deficiency_rules,
    cr.recommendation_plans,
    cr.input_options_schema,
    cr.premium_factor_matrix,
    cr.formula_explanation,
    1 - (cr.embedding <=> query_embedding) AS similarity
  FROM public.insurance_calculation_rules cr
  WHERE cr.embedding IS NOT NULL
    AND 1 - (cr.embedding <=> query_embedding) > match_threshold
  ORDER BY cr.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ----------------------------------------------------------------------------
-- 6. RLS 보안 및 권한 자동 적용
-- ----------------------------------------------------------------------------
ALTER TABLE public.insurance_knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insurance_calculation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insurance_rate_tables ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to knowledge base" ON public.insurance_knowledge_base;
DROP POLICY IF EXISTS "Allow public read access to calculation rules" ON public.insurance_calculation_rules;
DROP POLICY IF EXISTS "Allow public read access to rate tables" ON public.insurance_rate_tables;
DROP POLICY IF EXISTS "Allow service role write access to knowledge base" ON public.insurance_knowledge_base;
DROP POLICY IF EXISTS "Allow service role write access to calculation rules" ON public.insurance_calculation_rules;
DROP POLICY IF EXISTS "Allow service role write access to rate tables" ON public.insurance_rate_tables;

CREATE POLICY "Allow public read access to knowledge base" ON public.insurance_knowledge_base FOR SELECT USING (true);
CREATE POLICY "Allow public read access to calculation rules" ON public.insurance_calculation_rules FOR SELECT USING (true);
CREATE POLICY "Allow public read access to rate tables" ON public.insurance_rate_tables FOR SELECT USING (true);

CREATE POLICY "Allow service role write access to knowledge base" ON public.insurance_knowledge_base FOR ALL USING (true);
CREATE POLICY "Allow service role write access to calculation rules" ON public.insurance_calculation_rules FOR ALL USING (true);
CREATE POLICY "Allow service role write access to rate tables" ON public.insurance_rate_tables FOR ALL USING (true);
